import { StyleSheet } from "react-native";

export const hikerRegistrationStyles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    backgroundColor: "#070e08",
  },
  screen: {
    padding: 24,
    gap: 16,
    minHeight: "100%",
    backgroundColor: "#0d2010",
  },
  topGlow: {
    position: "absolute",
    top: -90,
    right: -60,
    width: 220,
    height: 220,
    borderRadius: 999,
    backgroundColor: "rgba(74, 158, 77, 0.22)",
  },
  bottomGlow: {
    position: "absolute",
    bottom: -110,
    left: -70,
    width: 250,
    height: 250,
    borderRadius: 999,
    backgroundColor: "rgba(96, 215, 100, 0.12)",
  },
  backButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  backButtonArrow: {
    color: "#ffffffcc",
    fontSize: 20,
    fontWeight: "700",
  },
  backButtonText: {
    color: "#ffffff99",
    fontSize: 14,
    fontWeight: "600",
  },
  header: {
    gap: 6,
  },
  headerTitle: {
    color: "#ffffff",
    fontSize: 38,
    lineHeight: 42,
    fontWeight: "900",
    letterSpacing: -1,
  },
  headerSubtitle: {
    color: "#ffffffb8",
    fontSize: 12,
  },
  avatarSection: {
    alignItems: "center",
    gap: 8,
    paddingTop: 8,
  },
  avatarLabel: {
    color: "#ffffffb2",
    fontSize: 12,
    fontWeight: "600",
  },
  avatarCard: {
    width: "100%",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.06)",
    padding: 16,
    gap: 14,
    alignItems: "center",
  },
  avatarCircle: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.25)",
    borderStyle: "dashed",
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarInitials: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "900",
  },
  avatarCopy: {
    alignItems: "center",
    gap: 4,
  },
  avatarTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
  },
  avatarHint: {
    color: "#ffffff80",
    fontSize: 11,
    textAlign: "center",
    lineHeight: 16,
  },
  photoButton: {
    minWidth: 156,
    borderRadius: 16,
    backgroundColor: "#4a9e4d",
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  photoButtonPressed: {
    opacity: 0.88,
  },
  photoButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  photoLinkButton: {
    paddingVertical: 2,
    paddingHorizontal: 4,
  },
  photoLinkButtonPressed: {
    opacity: 0.75,
  },
  photoLinkText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
    textDecorationLine: "underline",
  },
  formStack: {
    gap: 14,
    paddingTop: 4,
  },
  field: {
    gap: 8,
  },
  fieldLabel: {
    color: "#ffffffb2",
    fontSize: 12,
    fontWeight: "600",
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  input: {
    flex: 1,
    minHeight: 52,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    backgroundColor: "rgba(255,255,255,0.1)",
    color: "#ffffff",
    paddingHorizontal: 16,
    fontSize: 14,
  },
  endAdornment: {
    alignSelf: "stretch",
    justifyContent: "center",
  },
  passwordToggleText: {
    color: "#ffffffb8",
    fontSize: 12,
    fontWeight: "700",
  },
  emergencyCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(255,255,255,0.06)",
    padding: 16,
    gap: 12,
  },
  emergencyLabel: {
    color: "#ffffff80",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  formStackInner: {
    gap: 12,
  },
  submitWrap: {
    gap: 12,
    paddingTop: 8,
  },
  submitButton: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  submitButtonPressed: {
    opacity: 0.9,
  },
  submitButtonText: {
    color: "#1c3a1e",
    fontSize: 14,
    fontWeight: "800",
  },
  loginPrompt: {
    color: "#ffffff80",
    fontSize: 14,
    textAlign: "center",
  },
  loginLink: {
    color: "#ffffff",
    fontWeight: "800",
  },
});
