import { StyleSheet } from "react-native";

export const landingStyles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    backgroundColor: "#070e08",
  },
  shell: {
    padding: 18,
    gap: 16,
  },
  glowTop: {
    position: "absolute",
    top: -100,
    left: -70,
    width: 240,
    height: 240,
    borderRadius: 999,
    backgroundColor: "rgba(96, 215, 100, 0.12)",
  },
  glowBottom: {
    position: "absolute",
    bottom: -90,
    right: -80,
    width: 240,
    height: 240,
    borderRadius: 999,
    backgroundColor: "rgba(74, 158, 77, 0.18)",
  },
  heroCard: {
    borderRadius: 28,
    padding: 22,
    backgroundColor: "#0a1710",
    borderWidth: 1,
    borderColor: "rgba(128, 194, 231, 0.12)",
    gap: 16,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
  },
  brandMark: {
    width: 28,
    height: 28,
    borderRadius: 12,
    backgroundColor: "#4a9e4d",
    alignItems: "center",
    justifyContent: "center",
  },
  brandDot: {
    width: 14,
    height: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.75)",
  },
  brandText: {
    fontSize: 14,
    fontWeight: "700",
    flexShrink: 1,
  },
  brandTextLight: {
    color: "#e4ebe0",
  },
  brandTextAccent: {
    color: "#60d764",
  },
  livePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(96, 215, 100, 0.5)",
    backgroundColor: "rgba(74, 158, 77, 0.25)",
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#5fd664",
    opacity: 0.85,
  },
  liveText: {
    color: "#5fd664",
    fontSize: 10,
    fontWeight: "600",
  },
  heroCopy: {
    gap: 10,
  },
  heroKicker: {
    color: "#4a9e4d",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  heroTitle: {
    color: "#e4ebe0",
    fontSize: 40,
    lineHeight: 40,
    fontWeight: "900",
    letterSpacing: -1,
  },
  heroTitleAccent: {
    color: "#4a9e4d",
  },
  heroNote: {
    color: "#b9d5e7",
    fontSize: 13,
    lineHeight: 20,
  },
  sectionBlock: {
    gap: 10,
  },
  primaryButton: {
    backgroundColor: "#4a9e4d",
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: "rgba(228, 235, 224, 0.15)",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: "#e4ebe0",
    fontSize: 14,
    fontWeight: "700",
  },
  buttonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  statRow: {
    flexDirection: "row",
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(74, 158, 77, 0.15)",
    backgroundColor: "#0e1c10",
  },
  statCard: {
    flex: 1,
    paddingVertical: 16,
    alignItems: "center",
    gap: 4,
  },
  statCardBorder: {
    borderRightWidth: 1,
    borderRightColor: "rgba(74, 158, 77, 0.15)",
  },
  statValue: {
    color: "#e4ebe0",
    fontSize: 24,
    fontWeight: "900",
  },
  statLabel: {
    color: "#7a9477",
    fontSize: 9,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  sectionList: {
    gap: 12,
    paddingTop: 6,
  },
  sectionEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionEyebrowLine: {
    width: 20,
    height: 1,
    backgroundColor: "#4a9e4d",
  },
  sectionEyebrowText: {
    color: "#4a9e4d",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  sectionTitle: {
    color: "#e4ebe0",
    fontSize: 30,
    lineHeight: 30,
    fontWeight: "900",
    letterSpacing: -1,
  },
  sectionTitleAccent: {
    color: "#4a9e4d",
  },
  peakCard: {
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(74, 158, 77, 0.12)",
    backgroundColor: "#0e1c10",
  },
  peakHeader: {
    minHeight: 180,
    padding: 14,
    justifyContent: "space-between",
  },
  peakGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.85,
  },
  tagRow: {
    flexDirection: "row",
    gap: 6,
    flexWrap: "wrap",
    zIndex: 1,
  },
  tagPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(228, 235, 224, 0.15)",
    backgroundColor: "rgba(7, 14, 8, 0.75)",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  tagText: {
    color: "rgba(228, 235, 224, 0.88)",
    fontSize: 10,
    fontWeight: "600",
  },
  peakHeaderBottom: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    zIndex: 1,
    gap: 10,
  },
  peakName: {
    color: "#e4ebe0",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(74, 158, 77, 0.3)",
    backgroundColor: "rgba(74, 158, 77, 0.18)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#4a9e4d",
  },
  statusText: {
    color: "#4a9e4d",
    fontSize: 10,
    fontWeight: "700",
  },
  peakBody: {
    padding: 14,
    gap: 14,
  },
  metricGrid: {
    flexDirection: "row",
    gap: 8,
  },
  metricCard: {
    flex: 1,
    minWidth: 0,
    borderRadius: 18,
    padding: 10,
    borderWidth: 1,
    borderColor: "rgba(74, 158, 77, 0.12)",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  metricLabel: {
    color: "#7a9477",
    fontSize: 9,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "700",
  },
  metricValue: {
    paddingTop: 4,
    color: "#e4ebe0",
    fontSize: 12,
    fontWeight: "700",
  },
  planButton: {
    borderRadius: 20,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  planButtonSelected: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.32)",
  },
  planButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  benefitCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(74, 158, 77, 0.12)",
    backgroundColor: "#0e1c10",
    padding: 16,
  },
  benefitIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(74, 158, 77, 0.15)",
  },
  benefitIconText: {
    color: "#dff7ff",
    fontWeight: "900",
  },
  benefitCopy: {
    flex: 1,
  },
  benefitTitle: {
    color: "#e4ebe0",
    fontSize: 14,
    fontWeight: "700",
  },
  benefitDescription: {
    paddingTop: 4,
    color: "#7a9477",
    fontSize: 12,
    lineHeight: 18,
  },
  benefitIndex: {
    paddingTop: 8,
    color: "rgba(74, 158, 77, 0.7)",
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    fontWeight: "700",
  },
  registrationCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(74, 158, 77, 0.2)",
    padding: 20,
    gap: 10,
    backgroundColor: "#111f14",
  },
  registrationKicker: {
    color: "#4a9e4d",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  registrationTitle: {
    color: "#e4ebe0",
    fontSize: 26,
    lineHeight: 27,
    fontWeight: "900",
    letterSpacing: -1,
  },
  registrationTitleAccent: {
    color: "#4a9e4d",
  },
  registrationButtons: {
    paddingTop: 8,
    gap: 10,
  },
  registrationNote: {
    paddingTop: 2,
    textAlign: "center",
    color: "#7a9477",
    fontSize: 10,
    lineHeight: 15,
  },
  footer: {
    borderTopWidth: 1,
    borderTopColor: "rgba(74, 158, 77, 0.08)",
    alignItems: "center",
    gap: 8,
    paddingTop: 12,
    paddingBottom: 20,
  },
  footerBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingTop: 4,
  },
  footerMark: {
    width: 20,
    height: 20,
    borderRadius: 14,
    backgroundColor: "#4a9e4d",
    alignItems: "center",
    justifyContent: "center",
  },
  footerDot: {
    width: 11,
    height: 11,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.75)",
  },
  footerBrandText: {
    color: "#e4ebe0",
    fontSize: 12,
    fontWeight: "700",
  },
  footerCopy: {
    color: "rgba(122, 148, 119, 0.8)",
    fontSize: 10,
    lineHeight: 15,
    textAlign: "center",
  },
  actionPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.04)",
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  actionPillText: {
    color: "rgba(228, 235, 224, 0.85)",
    fontSize: 10,
  },
});
