import { StyleSheet } from "react-native";

export const loginPageStyles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    backgroundColor: "#070e08",
  },
  screen: {
    minHeight: "100%",
    padding: 24,
    backgroundColor: "#0d2010",
    justifyContent: "center",
  },
  backdropTop: {
    position: "absolute",
    top: -100,
    left: -80,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: "rgba(96, 215, 100, 0.16)",
  },
  backdropBottom: {
    position: "absolute",
    bottom: -110,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: "rgba(74, 158, 77, 0.16)",
  },
  surface: {
    borderRadius: 30,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(10, 23, 16, 0.94)",
    padding: 22,
    gap: 18,
  },
  backButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 2,
  },
  backButtonPressed: {
    opacity: 0.8,
  },
  backArrow: {
    color: "#ffffffcc",
    fontSize: 18,
    fontWeight: "700",
  },
  backText: {
    color: "#ffffff99",
    fontSize: 14,
    fontWeight: "600",
  },
  header: {
    gap: 4,
  },
  kicker: {
    color: "#4a9e4d",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  title: {
    color: "#ffffff",
    fontSize: 40,
    lineHeight: 42,
    fontWeight: "900",
    letterSpacing: -1,
  },
  subtitle: {
    color: "#ffffff80",
    fontSize: 14,
    lineHeight: 20,
  },
  form: {
    gap: 14,
    paddingTop: 8,
  },
  field: {
    gap: 8,
  },
  fieldLabel: {
    color: "#ffffffb2",
    fontSize: 12,
    fontWeight: "600",
  },
  fieldShell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 14,
    minHeight: 54,
  },
  fieldIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(74, 158, 77, 0.18)",
    borderWidth: 1,
    borderColor: "rgba(96, 215, 100, 0.28)",
    alignItems: "center",
    justifyContent: "center",
  },
  fieldIconText: {
    color: "#e4ebe0",
    fontSize: 12,
    fontWeight: "800",
  },
  input: {
    flex: 1,
    minWidth: 0,
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "400",
    paddingVertical: 0,
  },
  endAdornment: {
    justifyContent: "center",
  },
  passwordToggle: {
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  passwordTogglePressed: {
    opacity: 0.75,
  },
  passwordToggleText: {
    color: "#ffffffb8",
    fontSize: 12,
    fontWeight: "700",
  },
  submitButton: {
    borderRadius: 18,
    backgroundColor: "#ffffff",
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  submitButtonPressed: {
    opacity: 0.9,
  },
  submitButtonText: {
    color: "#1c3a1e",
    fontSize: 14,
    fontWeight: "800",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    paddingHorizontal: 4,
    paddingTop: 2,
  },
  footerText: {
    flexShrink: 1,
    color: "#ffffff80",
    fontSize: 14,
    lineHeight: 20,
  },
  footerLink: {
    color: "#ffffff",
    fontWeight: "800",
  },
  recoveryLink: {
    color: "#8fb7ff",
    fontSize: 14,
    fontWeight: "700",
  },
  statusText: {
    color: "#b8d5b8",
    fontSize: 12,
    lineHeight: 18,
    minHeight: 18,
  },
});
